version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - '19200:9200'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9200 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - '8100:8100'

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - '3100:80'
